name: CI/CD

on:
  pull_request:
    branches:
      - main
      - develop  
  push:
    branches:
      - main
      - develop

jobs:
  main:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install gems
        run: |
          bundler install

      - name: Prepare database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rails db:prepare

      - name: Run system tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
          bundle exec rails test:system

      # - name: Run rspec tests 
      #   env:
      #     PGHOST: localhost
      #     PGUSER: postgres
      #     PGPASSWORD: postgres
      #     RAILS_ENV: test
      #   run: |
      #     bundle exec rspec

      - name: Run rubocop 
        run: |
          bundle exec rubocop
